### ISSUE TITLE
Had to change Image.py

### ISSUE THREAD

**Issue by elbojvv** [2sh/StereoscoPy#1]
Got in working on Linux Mint 19.2, by changing in .local/lib/python2.7/site-packages/PIL/Image.py:

Line 1968: rotn_center = (int(w / 2.0), int(h / 2.0))
Line 2387: self.im.transform2(( int(box[0]),int(box[1]),int(box[2]),int(box[3]) ), image.im, method, data, resample, fill)
Line 2495: return Image()._new(core.new(mode, (int(size[0]),int(size[1])) ))

**Comment by 2sh** [comment]
I not a dev of the Pillow/PIL library
