### ISSUE TITLE
how to convert stereo pair from depthmap

### ISSUE THREAD

**Issue by Rishi5583** [2sh/StereoscoPy#4]
how to do right pair prediction in python from left image and depthmap ,it will be very helpful , if you find in solution python ,gpu.
Thanks..

**Comment by cmahnke** [comment]
You can try to implement it yourself:
* This is a good starting point: https://github.com/pairote/stereo2depth
* The background is described here: https://docs.opencv.org/4.9.0/d3/d14/tutorial_ximgproc_disparity_filtering.html

For better results make sure to pass (auto) alingned images.

**Comment by 2sh** [comment]
Creating depth maps is not in the scope of this project. The purpose of this project is for "creating or enhancing the illusion of depth" from an image pair.
The links by cmahnke do look like a good starting point though.
